### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by raphaelvigee** [charmbracelet/bubbletea#439]
Not exactly sure what triggers it, happens every now and then

```
Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
        /me/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.0/tea.go:371 +0x95
panic({0xfc8380, 0x1ba25b0})
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
fmt.(*buffer).writeString(...)
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/fmt/print.go:82
fmt.(*fmt).padString(0xc000dc5200?, {0x0, 0x52})
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/fmt/format.go:110 +0x247
fmt.(*fmt).fmtS(0x400?, {0x0?, 0x400?})
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/fmt/format.go:359 +0x3f
fmt.(*pp).fmtString(0x7fe2f255afff?, {0x0?, 0x7fe2f285fbd0?}, 0x400?)
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/fmt/print.go:443 +0x86
fmt.(*pp).printArg(0xc0061a8000, {0xf4dec0?, 0xc0013e50b0}, 0x76)
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/fmt/print.go:694 +0x60c
fmt.(*pp).doPrintf(0xc0061a8000, {0x113fdb0, 0xa}, {0xc000dc5520?, 0x3, 0x3})
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/fmt/print.go:1026 +0x288
fmt.Sprintf({0x113fdb0, 0xa}, {0xc000dc5520, 0x3, 0x3})
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/fmt/print.go:219 +0x59
heph/cmd.(*renderer).View(0xc004efab40)
        /project/sandbox/__target_build_linux_amd64/_dir/cmd/wait_pool.go:236 +0x61d
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc002986000)
        /me/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.0/tea.go:542 +0x12d8
github.com/charmbracelet/bubbletea.(*Program).Start(...)
        /me/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.0/tea.go:549
heph/cmd.PoolUI({0x11391bd, 0x3}, 0xc00e878b40, 0xc0000e8240)
        /project/sandbox/__target_build_linux_amd64/_dir/cmd/wait_pool.go:127 +0x3fb
heph/cmd.WaitPool({0x11391bd, 0x3}, 0xc00e878b40, 0x0)
        /project/sandbox/__target_build_linux_amd64/_dir/cmd/wait_pool.go:39 +0x153
heph/cmd.run({0x14407c8?, 0xc0000580b8}, {0xc005979c00?, 0x1f?, 0x0?}, 0x0?, 0x0)
        /project/sandbox/__target_build_linux_amd64/_dir/cmd/run.go:144 +0x19b
heph/cmd.glob..func31(0x1bb33c0, {0xc0003520b0?, 0x1, 0x1})
        /project/sandbox/__target_build_linux_amd64/_dir/cmd/root.go:225 +0x213
github.com/spf13/cobra.(*Command).execute(0x1bb33c0, {0xc0003520a0, 0x1, 0x1})
        /me/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x1bb2c40)
        /me/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /me/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
heph/cmd.execute()
        /project/sandbox/__target_build_linux_amd64/_dir/cmd/root.go:413 +0x25
heph/cmd.Execute()
        /project/sandbox/__target_build_linux_amd64/_dir/cmd/root.go:423 +0x1e
main.main()
        /project/sandbox/__target_build_linux_amd64/_dir/main.go:6 +0x17
```

**Comment by meowgorithm** [comment]
Hi! This is most likely an error in your program.

**Comment by raphaelvigee** [comment]
Oh whoops yeah my bad... For some reason i was under the impression the `tea.Printf` was to blame, closing!
