### ISSUE TITLE
Application not running

### ISSUE THREAD

**Issue by nghtstr** [charmbracelet/bubbletea#634]
I know that is not a descriptive title for this, but I have no other way of describing what I am seeing. I am getting the following output on what used to be a working application:

```
# golang.org/x/text/transform
SIGILL: illegal instruction
PC=0x43292c m=0 sigcode=2
instruction bytes: 0x45 0xe 0x57 0xff 0x64 0x4c 0x8b 0x34 0x25 0xf8 0xff 0xff 0xff 0x48 0x8b 0x6c

goroutine 0 [idle]:
runtime.wbBufFlush(0xc00003bc40?, 0x1e96ee4c?)
	/usr/lib/go/src/runtime/mwbbuf.go:200 +0x6c fp=0x7ffe88001560 sp=0x7ffe88001540 pc=0x43292c
runtime.gcDrainN(0xc00003bc40, 0x10000)
	/usr/lib/go/src/runtime/mgcmark.go:1174 +0x113 fp=0x7ffe88001590 sp=0x7ffe88001560 pc=0x41fe73
runtime.gcAssistAlloc1(0xc0000061a0, 0xc000124fe8?)
	/usr/lib/go/src/runtime/mgcmark.go:567 +0x12e fp=0x7ffe880015f8 sp=0x7ffe88001590 pc=0x41e98e
runtime.gcAssistAlloc.func1()
	/usr/lib/go/src/runtime/mgcmark.go:474 +0x25 fp=0x7ffe88001618 sp=0x7ffe880015f8 pc=0x41e845
runtime.systemstack()
	/usr/lib/go/src/runtime/asm_amd64.s:492 +0x49 fp=0x7ffe88001620 sp=0x7ffe88001618 pc=0x4680e9

goroutine 1 [GC assist marking]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:459 fp=0xc000124fd8 sp=0xc000124fd0 pc=0x468080
runtime.gcAssistAlloc(0xc0000061a0)
	/usr/lib/go/src/runtime/mgcmark.go:473 +0x1a5 fp=0xc000125038 sp=0xc000124fd8 pc=0x41e6e5
runtime.mallocgc(0x68, 0xce9720, 0x1)
	/usr/lib/go/src/runtime/malloc.go:906 +0x11f fp=0xc0001250b0 sp=0xc000125038 pc=0x40d01f
runtime.newobject(0xcc3920?)
	/usr/lib/go/src/runtime/malloc.go:1202 +0x27 fp=0xc0001250d8 sp=0xc0001250b0 pc=0x40d8e7
cmd/compile/internal/types2.NewFunc(...)
	/usr/lib/go/src/cmd/compile/internal/types2/object.go:382
cmd/compile/internal/types2.(*Checker).collectObjects(0xc000436000)
	/usr/lib/go/src/cmd/compile/internal/types2/resolver.go:424 +0x17a5 fp=0xc000125688 sp=0xc0001250d8 pc=0xba7085
cmd/compile/internal/types2.(*Checker).checkFiles(0xc000436000, {0xc000012790, 0x1, 0x1})
	/usr/lib/go/src/cmd/compile/internal/types2/check.go:321 +0x12c fp=0xc000125700 sp=0xc000125688 pc=0xb72ccc
cmd/compile/internal/types2.(*Checker).Files(...)
	/usr/lib/go/src/cmd/compile/internal/types2/check.go:299
cmd/compile/internal/types2.(*Config).Check(0xc000011a10?, {0x7ffe880036d6?, 0xff?}, {0xc000012790, 0x1, 0x1}, 0x7f01b43dcfff?)
	/usr/lib/go/src/cmd/compile/internal/types2/api.go:416 +0x70 fp=0xc000125750 sp=0xc000125700 pc=0xb62bd0
cmd/compile/internal/noder.checkFiles({0xc000012460, 0x1, 0x203000?})
	/usr/lib/go/src/cmd/compile/internal/noder/irgen.go:64 +0x45c fp=0xc000125898 sp=0xc000125750 pc=0xbe6d3c
cmd/compile/internal/noder.check2({0xc000012460, 0x1, 0x1})
	/usr/lib/go/src/cmd/compile/internal/noder/irgen.go:77 +0x46 fp=0xc0001259c0 sp=0xc000125898 pc=0xbe7006
cmd/compile/internal/noder.LoadPackage({0xc0000023a0, 0x1, 0x2})
	/usr/lib/go/src/cmd/compile/internal/noder/noder.go:82 +0x48f fp=0xc000125ad8 sp=0xc0001259c0 pc=0xbeb24f
cmd/compile/internal/gc.Main(0xd6c3c0)
	/usr/lib/go/src/cmd/compile/internal/gc/main.go:189 +0xbbd fp=0xc000125f20 sp=0xc000125ad8 pc=0xc4f01d
main.main()
	/usr/lib/go/src/cmd/compile/main.go:57 +0xdd fp=0xc000125f80 sp=0xc000125f20 pc=0xc772fd
runtime.main()
	/usr/lib/go/src/runtime/proc.go:250 +0x212 fp=0xc000125fe0 sp=0xc000125f80 pc=0x43a092
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000125fe8 sp=0xc000125fe0 pc=0x46a161

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:363 +0xd6 fp=0xc000056fb0 sp=0xc000056f90 pc=0x43a456
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/lib/go/src/runtime/proc.go:302 +0xad fp=0xc000056fe0 sp=0xc000056fb0 pc=0x43a2ed
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000056fe8 sp=0xc000056fe0 pc=0x46a161
created by runtime.init.6
	/usr/lib/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:363 +0xd6 fp=0xc000057790 sp=0xc000057770 pc=0x43a456
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/lib/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000577c8 sp=0xc000057790 pc=0x424f8e
runtime.gcenable.func1()
	/usr/lib/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000577e0 sp=0xc0000577c8 pc=0x419c46
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000577e8 sp=0xc0000577e0 pc=0x46a161
created by runtime.gcenable
	/usr/lib/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [runnable]:
runtime.gopark(0xc000074000?, 0xea5398?, 0x1?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:363 +0xd6 fp=0xc000057f70 sp=0xc000057f50 pc=0x43a456
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x13cf340)
	/usr/lib/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000057fa0 sp=0xc000057f70 pc=0x423033
runtime.bgscavenge(0x0?)
	/usr/lib/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000057fc8 sp=0xc000057fa0 pc=0x423605
runtime.gcenable.func2()
	/usr/lib/go/src/runtime/mgc.go:179 +0x26 fp=0xc000057fe0 sp=0xc000057fc8 pc=0x419be6
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x46a161
created by runtime.gcenable
	/usr/lib/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0xc000056670?, 0xeb?, 0x70?, 0xc000056770?)
	/usr/lib/go/src/runtime/proc.go:363 +0xd6 fp=0xc000056628 sp=0xc000056608 pc=0x43a456
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/lib/go/src/runtime/mfinal.go:180 +0x10f fp=0xc0000567e0 sp=0xc000056628 pc=0x418d4f
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x46a161
created by runtime.createfing
	/usr/lib/go/src/runtime/mfinal.go:157 +0x45
```

Here is GIST to the full output: [https://gist.github.com/nghtstr/84b19044d6a60454482e3162aacde827](https://gist.github.com/nghtstr/84b19044d6a60454482e3162aacde827)

**Comment by muesli** [comment]
This happens when you're trying to run a binary that's using CPU instructions (SSE, AVX, etc.) that are not available on the target platform. Did you compile this on the same machine you're trying to run it on?

**Comment by nghtstr** [comment]
Yes. I am literally doing `go run .`

**Comment by nghtstr** [comment]
Apparently, my kernel freaked out. The solution to this problem is to reboot your machine.

BTW, Bubble Tea is really awesome!!
