### ISSUE TITLE
"open /dev/tty: no such device or address" when running in Docker with no tty

### ISSUE THREAD

**Issue by jonbretman** [charmbracelet/bubbletea#761]
**Describe the bug**
It seems that when running inside a Docker container with no tty `Run()` returns an error:

```
open /dev/tty: no such device or address
```

**Setup**
Please complete the following information along with version numbers, if applicable.
 - Ubuntu (docker)

**To Reproduce**
Simple bubbletea program:
```go
package main

import (
	tea "github.com/charmbracelet/bubbletea"
)

type Model struct{}

func (m Model) Init() tea.Cmd {
	return nil
}

func (m Model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	return m, tea.Quit
}

func (m Model) View() string {
	return ""
}

func main() {
	_, err := tea.NewProgram(Model{}).Run()
	if err != nil {
		panic(err)
	}
}

```

Build the binary for linux: `GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./main ./main.go`

Run in Docker: `docker run -v "$(pwd)"/main:/usr/local/bin/my-cli public.ecr.aws/ubuntu/ubuntu:22.04 my-cli`

```
panic: open /dev/tty: no such device or address

goroutine 1 [running]:
main.main()
	/Users/jonbretman/code/bubbletea-tty-issue/main.go:24 +0x53
```

I'm using AWS Ubuntu because I discovered this issue while using my CLI tool in AWS CodeBuild, but the issue is not specific to AWS or CodeBuild (as far as I can tell). Running with `-it` works e.g. `docker run -it ...`

**Expected behavior**
I would expect the program to still run

**Comment by meowgorithm** [comment]
This came up [in Discord](https://discord.com/channels/1032368467246075914/1123965681549967440/1123965681549967440) recently as well. Based on this and that I don't think we should fatally error if we're not able to open a TTY. To help work around any resulting confusion we may want to consider:

1. Exposing input on `Program` (i.e. `Program.Input() io.Reader` … `nil` would mean no input)
2. Send something like a `WarningNoInputMsg` on program start if no input can be detected.

Also note that internally, if input's not a TTY, we try and open a TTY at `/dev/tty` (or `CONIN$` on Windows).

Fwiw, to some degree you can work around this in the meantime by detecting presence of a TTY prior to starting the program and passing `tea.WithInput(nil)` to `NewProgram` if no TTY is available.

**Comment by DavidS-ovm** [comment]
`tea.WithInput(nil)` does not work when using `tea.Exec()` on 0.26.5:

```
 goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.22.4/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.22.4/x64/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:479 +0x91
panic({0x3ffa560?, 0x68a0570?})
	/opt/hostedtoolcache/go/1.22.4/x64/src/runtime/panic.go:770 +0x132
github.com/charmbracelet/bubbletea.(*Program).ReleaseTerminal(0xc000018900)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:655 +0x30
github.com/charmbracelet/bubbletea.(*Program).exec(0xc000018900, {0x4f2c308, 0xc0009c2470}, 0xc00041ef90)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/exec.go:103 +0x2b
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc000018900, {0x4f2a370?, 0xc000018800?}, 0xc0001145a0)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:366 +0x4b0
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000018900)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.5/tea.go:550 +0xa0e
```

**Comment by jgardona** [comment]
Found the same issue today on fedora. Cant debug with delve.

**Comment by meowgorithm** [comment]
@jgardona (anyone encountering this issue): would you mind supplying a minimal source of your Dockerfile and source code that produces to help debug? Without that context it will
Be very hard for us to look into this one.

**Comment by jgardona** [comment]
> [@jgardona](https://github.com/jgardona) (and anyone else encountering this issue): would you mind supplying a minimal source of your Dockerfile and source code that produces to help debug? Without that context it will Be very hard for us to look into this one.

Hello, good evening.

The code is just the commands example from bubbletea:

```go
package main

import (
	"fmt"
	"net/http"
	"time"

	tea "github.com/charmbracelet/bubbletea"
)

const url = "https://charm.sh/"

type model struct {
	status int
	err    error
}

func checkServer() tea.Msg {
	c := &http.Client{Timeout: 10 * time.Second}
	res, err := c.Get(url)
	if err != nil {
		return errMsg{err}
	}
	return statusMsg(res.StatusCode)
}

type statusMsg int
type errMsg struct{ err error }

func (e errMsg) Error() string { return e.err.Error() }

func (m model) Init() tea.Cmd {
	return checkServer
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case statusMsg:
		m.status = int(msg)
		return m, tea.Quit
	case errMsg:
		m.err = msg
		return m, tea.Quit
	case tea.KeyMsg:
		if msg.Type == tea.KeyCtrlC {
			return m, tea.Quit
		}
	}
	return m, nil
}

func (m model) View() string {
	if m.err != nil {
		return fmt.Sprintf("\nWe had some trouble: %v\n\n", m.err)
	}
	s := fmt.Sprintf("Checking %s ...", url)
	if m.status > 0 {
		s += fmt.Sprintf("%d %s!", m.status, http.StatusText(m.status))
	}
	return "\n" + s + "\n\n"
}

func main() {
	if _, err := tea.NewProgram(model{}).Run(); err != nil {
		panic(err)
	}

}
```

The issue happens when stars the debug:

![Image](https://github.com/user-attachments/assets/1a9f3c9d-1a86-4f2a-bd89-bba696e12dab)


![Image](https://github.com/user-attachments/assets/8589102e-cc67-499d-b32a-0d476a5dea75)

It fails with the same message:

![Image](https://github.com/user-attachments/assets/19fb8207-6eee-4725-aa53-9a135e8925fb)

**Comment by meowgorithm** [comment]
Hi! Bubble Tea needs a tty in order to read input and render output, so you'll need to run the container with the `-it` flag (i.e. `docker run -it image`).

To debug with `delve` [you'll need to run it headless](https://github.com/charmbracelet/bubbletea?tab=readme-ov-file#debugging-with-delve).
