### ISSUE TITLE
Filtering panic

### ISSUE THREAD

**Issue by guidoenr** [charmbracelet/bubbletea#826]
Hey guys, how are you? hope you're doing good :)

I assume this is **not** the correct place to ask this question, but I didn't find any other place to ask it, and maybe this is also a bug.

We are using your model to display an application to handle **tests jobs**, which are listed in the dash view in the following way:
![image](https://github.com/charmbracelet/bubbletea/assets/47611900/c45e3d49-f2d3-4d7d-97b1-f3a9f81330a4)

Note the `/ filter` key:

Looking at the code, seems like it was never implemented and the model is displaying it anyway.
I was thinking maybe this is a `default` thing, where it automatically set a filter key to the model.

And when i type `/` to enter a filter value and then fill it with some text:
![image](https://github.com/charmbracelet/bubbletea/assets/47611900/858071ae-d6dc-4ca8-a919-bf06abb53560)

I got the following error:
```bash
panic: runtime error: invalid memory address or nil pointer dereference                                                                                            
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5e4508]

goroutine 861 [running]:
github.com/charmbracelet/bubbles/list.filterItems.func1()
	/home/guido/go/pkg/mod/github.com/charmbracelet/bubbles@v0.16.1/list/list.go:1211 +0x1a8
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
	/home/guido/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:268 +0x38
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1
	/home/guido/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:267 +0x14d
```

So that's it - 
I would like to know if there are some examples of how to filter, or how to implement this because it looks truly useful.
The use case will be simple: -> a user types their desired text to filter and then only shows those things filtered

Searched at https://github.com/charmbracelet/bubbletea/tree/master/examples and I didn't find what I want.

**Comment by kpetremann** [comment]
Hello @guidoenr,
I am encountering an issue with the exact same stacktrace than you have.
Did you find the root cause of it?

On my side, it looks like the issue is coming from RemoveItem method. When I don't use it, there is no issue at all.

**Comment by muesli** [comment]
The list's `Item` interface defines a `FilterValue` function that you can implement to allow for filtering custom structs and elements.

**Comment by bad-noodles** [comment]
I had this issue when some nil values got into the array I passed to the list, thinking it was a proper item.
